### ISSUE TITLE
Preply

### ISSUE THREAD

**Issue by ejmalsi** [yvoronoy/awesome-english#28]
Preply

Il tuo insegnante di lingua — Scopri il metodo Preply per parlare una lingua con sicurezza. Trova l'insegnante ideale. Impara una lingua con un insegnante focalizzato sui tuoi obiettivi. Trova un insegnante. Marketplace di insegnanti. Tutti i Livelli. Facile da iniziare. Corsi Online. Lezioni per tutte le età

**Comment by yvoronoy** [comment]
Added Preply,
Thanks
